### ISSUE TITLE
[packagers] Flatpak packager generates invalid url types

### ISSUE THREAD

**Issue by crschnick** [jreleaser/jreleaser#1331] opened 2023-04-17 01:24 UTC
I encountered this error trying to install a generated flakpak package:

    Renaming io.xpipe.app.metainfo.xml to share/appdata/io.xpipe.app.appdata.xml
    Running appstream-compose
    Processing application io.xpipe.app
    io.xpipe.app:                      AppData problem: tag-invalid : <url> type invalid [unknown]
    Error loading AppData file: AppData file /app/share/appdata/io.xpipe.app.appdata.xml was not valid

It definitely has something to do with these entries as it works when I remove them:
  
    <url type="homepage">https://github.com/xpipe-io/xpipe</url>
    <url type="documentation">https://xpipe.io/docs</url>
    <url type="license">https://github.com/xpipe-io/xpipe/blob/master/LICENSE.md</url>
    <url type="bugtracker">https://github.com/xpipe-io/xpipe/issues</url>
    <url type="vcs-browser">https://github.com/xpipe-io/xpipe</url>
    <url type="contribute">https://github.com/xpipe-io/xpipe/CONTRIBUTING.md</url>

I guess some of the types don't match up with the documentation: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

**Comment by aalmiray** [comment] 2023-04-17 07:38
Duplicate of https://github.com/jreleaser/jreleaser/issues/1266

**Closed by aalmiray** 2023-04-17 07:38 UTC
Labels: bug, duplicate
