### ISSUE TITLE
NullPointerException assembling with jreleaser-maven-plugin

### ISSUE THREAD

**Issue by jandroav** [jreleaser/jreleaser#1400] opened 2023-05-31 14:37 UTC
### Task List

- [x] Steps to reproduce provided
- [x] Stacktrace (if present) provided
- [x] Example that reproduces the problem (link to git repository is ideal)
- [x] Full description of the issue provided (see below)

### Steps to Reproduce

With the following `pom.xml` configuration:

```xml
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jdks-maven-plugin</artifactId>
                <version>1.6.0</version>
                <inherited>false</inherited>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>setup-disco</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <pkgs>
                        <pkg>
                            <name>zulu11Linux</name>
                            <platform>linux-x86_64</platform>
                            <version>11.0.11</version>
                        </pkg>
                        <pkg>
                            <name>zulu11Osx</name>
                            <platform>osx-x86_64</platform>
                            <version>11.0.11</version>
                        </pkg>
                        <pkg>
                            <name>zulu11Windows</name>
                            <platform>windows-x86_64</platform>
                            <version>11.0.11</version>
                        </pkg>
                    </pkgs>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <version>1.6.0</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>prepare</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <jreleaser>
                            <distributions>
                                <liquibase>
                                    <type>SINGLE_JAR</type>
                                    <stereotype>CLI</stereotype>
                                    <artifacts>
                                        <artifact>
                                            <path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>
                                        </artifact>
                                    </artifacts>
                                </liquibase>
                            </distributions>
                            <assemble>
                                <jlink>
                                    <liquibase>
                                        <active>ALWAYS</active>
                                        <exported>true</exported>
                                        <imageName>liquibase-{{projectVersion}}</imageName>
                                        <executable>liquibase</executable>
                                        <stereotype>CLI</stereotype>
                                        <targetJdks>
                                            <targetJdk>
                                                <path>${jdk.pathPrefix}/zulu11Osx/${jdk.filePrefix}-macosx_x64/zulu-11.jdk/Contents/Home</path>
                                                <platform>osx-x86_64</platform>
                                            </targetJdk>
                                            <targetJdk>
                                                <path>${jdk.pathPrefix}/zulu11Linux/${jdk.filePrefix}-linux_x64</path>
                                                <platform>linux-x86_64</platform>
                                            </targetJdk>
                                            <targetJdk>
                                                <path>${jdk.pathPrefix}/zulu11Windows/${jdk.filePrefix}-win_x64</path>
                                                <platform>windows-x86_64</platform>
                                            </targetJdk>
                                        </targetJdks>
                                        <mainJar>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</mainJar>
                                    </liquibase>
                                </jlink>
                            </assemble>
                        </jreleaser>
                    </configuration>
            </plugin>
```

Execute `mvn package -DskipTests`

### Expected Behaviour

No package/assemble errors

### Actual Behaviour

```bash
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:prepare (default) on project liquibase: Execution default of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:prepare failed: JReleaser has not been properly configured.: NullPointerException -> [Help 1]
```

`/target/jreleaser/trace.log` content shows the following:

```bash
[INFO]  JReleaser 1.6.0
------------------------------------------------------------
jreleaser 1.6.0
------------------------------------------------------------
Build time:   2023-04-29 09:09:27Z
Revision:     fccb6ee7cbf897dc19a0cceffd06db7f3b7ef708
JVM:          20.0.1 (Homebrew 20.0.1)
------------------------------------------------------------
[INFO]    - basedir set to /Users/jandro/workspace/liquibase/liquibase
[INFO]    - outputdir set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser
[DEBUG]   - basedir set to /Users/jandro/workspace/liquibase/liquibase
[DEBUG]   - baseOutputDirectory set to /Users/jandro/workspace/liquibase/liquibase/target
[DEBUG]   - outputDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser
[DEBUG]   - checksumDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/checksums
[DEBUG]   - catalogsDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/catalogs
[DEBUG]   - signaturesDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/signatures
[DEBUG]   - prepareDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/prepare
[DEBUG]   - packageDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/package
[DEBUG]   - downloadDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/download
[DEBUG]   - assembleDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/assemble
[DEBUG]   - artifactsDirectory set to /Users/jandro/workspace/liquibase/liquibase/target/jreleaser/artifacts
[INFO]  git-root-search set to false
[INFO]  Loading variables from /Users/jandro/.jreleaser/config.properties
[WARN]  Variables source /Users/jandro/.jreleaser/config.properties does not exist
[DEBUG] The following variables are defined in the current environment:
[DEBUG]   JRELEASER_GITHUB_TOKEN
[INFO]  Validating configuration
[INFO]  Strict mode set to false
[DEBUG] adjusting distributions with assemblies
[DEBUG]   [validation] --== ASSEMBLE ==--
[DEBUG]   [validation] hooks
[DEBUG]   [validation] hooks.command
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] hooks.script
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] - disabled
[DEBUG]   [validation] project
[DEBUG]   [validation] project.java
[DEBUG]   [validation] download
[DEBUG]   [validation] assemble
[DEBUG]   [validation] assemble.jlink
java.lang.NullPointerException: Cannot invoke "org.jreleaser.model.internal.assemble.JlinkAssembler.setName(String)" because the return value of "java.util.Map$Entry.getValue()" is null
	at org.jreleaser.model.internal.validation.assemble.JlinkAssemblerValidator.validateJlink(JlinkAssemblerValidator.java:55)
	at org.jreleaser.model.internal.validation.assemble.AssemblersValidator.validateAssemblers(AssemblersValidator.java:68)
	at org.jreleaser.model.internal.JReleaserModelValidator.validateModel(JReleaserModelValidator.java:69)
	at org.jreleaser.model.internal.JReleaserModelValidator.validate(JReleaserModelValidator.java:57)
	at org.jreleaser.model.internal.JReleaserContext.adjustDistributions(JReleaserContext.java:508)
	at org.jreleaser.model.internal.JReleaserContext.validateModel(JReleaserContext.java:481)
	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:47)
	at org.jreleaser.workflow.WorkflowImpl.<init>(WorkflowImpl.java:45)
	at org.jreleaser.workflow.Workflows.prepare(Workflows.java:112)
	at org.jreleaser.maven.plugin.JReleaserPrepareMojo.doExecute(JReleaserPrepareMojo.java:41)
	at org.jreleaser.maven.plugin.AbstractDistributionMojo.doExecute(AbstractDistributionMojo.java:44)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserPrepareMojo.execute(JReleaserPrepareMojo.java:31)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:910)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1921)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.jreleaser.model.internal.assemble.Assemble.getActiveJlinks(Assemble.java:199)
	at org.jreleaser.model.internal.assemble.Assemble.findAllAssemblers(Assemble.java:330)
	at org.jreleaser.model.internal.JReleaserContext.adjustDistributions(JReleaserContext.java:516)
	at org.jreleaser.model.internal.JReleaserContext.validateModel(JReleaserContext.java:481)
	at org.jreleaser.engine.context.ModelValidator.validate(ModelValidator.java:47)
	at org.jreleaser.workflow.WorkflowImpl.<init>(WorkflowImpl.java:45)
	at org.jreleaser.workflow.Workflows.prepare(Workflows.java:112)
	at org.jreleaser.maven.plugin.JReleaserPrepareMojo.doExecute(JReleaserPrepareMojo.java:41)
	at org.jreleaser.maven.plugin.AbstractDistributionMojo.doExecute(AbstractDistributionMojo.java:44)
	at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute(AbstractJReleaserMojo.java:109)
	at org.jreleaser.maven.plugin.JReleaserPrepareMojo.execute(JReleaserPrepareMojo.java:31)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:910)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:283)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:226)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:407)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:348)

```

It seems https://github.com/jreleaser/jreleaser/blob/5db74c1f2de426cfd4cd0707f6b9199c4a2b6514/core/jreleaser-model-impl/src/main/java/org/jreleaser/model/internal/validation/assemble/JlinkAssemblerValidator.java#L54 is not taking the defined `liquibase` jlink app name.

I don't see any other place to set the app name here: https://jreleaser.org/guide/latest/reference/assemble/jlink.html

### Environment Information

- **Operating System**: macOS Ventura 13.4
- **JReleaser Version:** 1.6.0
- **JDK Version:** OpenJDK Runtime Environment Temurin-11.0.14.1+1 (build 11.0.14.1+1)

**Comment by jandroav** [comment] 2023-05-31 20:46
Thanks @aalmiray. I will do it tomorrow and update this issue. 🙏🏻

**Comment by jandroav** [comment] 2023-05-31 21:07
This works:

```xml
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <version>1.6.0</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>prepare</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <jreleaser>
                            <distributions>
                                <liquibase>
                                    <type>SINGLE_JAR</type>
                                    <stereotype>CLI</stereotype>
                                    <artifacts>
                                        <artifact>
                                            <path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>
                                        </artifact>
                                    </artifacts>
                                </liquibase>
                            </distributions>
                            <assemble>
                                <jlink>
                                    <liquibase>
                                    </liquibase>
                                </jlink>
                            </assemble>
                        </jreleaser>
                    </configuration>
            </plugin>
```

But when adding `<path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>`:

```xml
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <version>1.6.0</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>prepare</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <jreleaser>
                            <distributions>
                                <liquibase>
                                    <type>SINGLE_JAR</type>
                                    <stereotype>CLI</stereotype>
                                    <artifacts>
                                        <artifact>
                                            <path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>
                                        </artifact>
                                    </artifacts>
                                </liquibase>
                            </distributions>
                            <assemble>
                                <jlink>
                                    <liquibase>
                                        <mainJar>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</mainJar>
                                    </liquibase>
                                </jlink>
                            </assemble>
                        </jreleaser>
                    </configuration>
            </plugin>
```

I get:

```bash
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config (default-cli) on project liquibase: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config failed: JReleaser has not been properly configured.: Cannot invoke "org.jreleaser.model.internal.assemble.JlinkAssembler.asMap(boolean)" because "d" is null -> [Help 1]
```

Also with the following:

```xml
            <plugin>
                <groupId>org.jreleaser</groupId>
                <artifactId>jreleaser-maven-plugin</artifactId>
                <version>1.6.0</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>prepare</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <jreleaser>
                            <distributions>
                                <liquibase>
                                    <type>SINGLE_JAR</type>
                                    <stereotype>CLI</stereotype>
                                    <artifacts>
                                        <artifact>
                                            <path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>
                                        </artifact>
                                    </artifacts>
                                </liquibase>
                            </distributions>
                            <assemble>
                                <jlink>
                                    <liquibase>
                                        <active>ALWAYS</active>
                                    </liquibase>
                                </jlink>
                            </assemble>
                        </jreleaser>
                    </configuration>
            </plugin>
```

I am getting:

```bash
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config (default-cli) on project liquibase: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config failed: JReleaser has not been properly configured.
[ERROR] jlink.liquibase.mainJar.path must not be null
[ERROR] project.description must not be blank
[ERROR] project.copyright must not be blank
```

That is ok but after filling `jlink.liquibase.mainJar.path`, `project.description` and `project.copyright` I get that `Cannot invoke "org.jreleaser.model.internal.assemble.JlinkAssembler.asMap(boolean)" because "d" is null`

`mvn jreleaser:config -Djreleaser.config.assembly=true -X` returns:

```bash
[ERROR] Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config (default-cli) on project liquibase: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config failed: JReleaser has not been properly configured.: Cannot invoke "org.jreleaser.model.internal.assemble.JlinkAssembler.asMap(boolean)" because "d" is null -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config (default-cli) on project liquibase: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config failed: JReleaser has not been properly configured.
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:347)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:config failed: JReleaser has not been properly configured.
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: org.jreleaser.model.JReleaserException: JReleaser has not been properly configured.
    at org.jreleaser.engine.context.ModelValidator.validate (ModelValidator.java:81)
    at org.jreleaser.maven.plugin.JReleaserConfigMojo.doExecute (JReleaserConfigMojo.java:73)
    at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute (AbstractJReleaserMojo.java:109)
    at org.jreleaser.maven.plugin.JReleaserConfigMojo.execute (JReleaserConfigMojo.java:37)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
Caused by: java.lang.NullPointerException: Cannot invoke "org.jreleaser.model.internal.assemble.JlinkAssembler.asMap(boolean)" because "d" is null
    at org.jreleaser.model.internal.assemble.Assemble.lambda$asMap$5 (Assemble.java:288)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:197)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
    at java.util.Iterator.forEachRemaining (Iterator.java:133)
    at java.util.Spliterators$IteratorSpliterator.forEachRemaining (Spliterators.java:1921)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ReduceOps$ReduceOp.evaluateSequential (ReduceOps.java:921)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.collect (ReferencePipeline.java:682)
    at org.jreleaser.model.internal.assemble.Assemble.asMap (Assemble.java:289)
    at org.jreleaser.model.internal.JReleaserModel.asMap (JReleaserModel.java:441)
    at org.jreleaser.engine.context.ModelValidator.validate (ModelValidator.java:50)
    at org.jreleaser.maven.plugin.JReleaserConfigMojo.doExecute (JReleaserConfigMojo.java:73)
    at org.jreleaser.maven.plugin.AbstractJReleaserMojo.execute (AbstractJReleaserMojo.java:109)
    at org.jreleaser.maven.plugin.JReleaserConfigMojo.execute (JReleaserConfigMojo.java:37)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:126)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:342)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:330)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:175)
    at org.apache.maven.lifecycle.internal.MojoExecutor.access$000 (MojoExecutor.java:76)
    at org.apache.maven.lifecycle.internal.MojoExecutor$1.run (MojoExecutor.java:163)
    at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute (DefaultMojosExecutionStrategy.java:39)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:160)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:105)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:73)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:53)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:118)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:261)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:173)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:101)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:910)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:283)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:206)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:283)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:226)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[DEBUG] Shutting down adapter factory; available factories [file-lock, rwlock-local, semaphore-local, noop]; available name mappers [discriminating, file-gav, file-hgav, file-static, gav, static]
```

**Comment by aalmiray** [comment] 2023-05-31 21:39
The `<mainJar>` DSL element is of type Artifact which means it requires a `<path>` element.

Use the following

```xml
                              <liquibase>
                                  <active>ALWAYS</active>
                                  <exported>true</exported>
                                  <imageName>liquibase-{{projectVersion}}</imageName>
                                  <executable>liquibase</executable>
                                  <stereotype>CLI</stereotype>
                                  <mainJar>
                                      <path>liquibase-cli/target/liquibase-cli-{{projectVersion}}.jar</path>
                                  </mainJar>
                              </liquibase>
```

A more complete example can be found at https://github.com/aalmiray/q-cli-jlink/blob/main/pom.xml which is linked from https://jreleaser.org/guide/latest/examples/jlink/index.html

**Comment by aalmiray** [comment] 2023-05-31 22:17
Duplicate of https://github.com/jreleaser/jreleaser/issues/1081

**Closed by aalmiray** 2023-05-31 22:17 UTC
Labels: bug, duplicate
