### ISSUE TITLE
CI Failure is not clear - probably cross repo access rights

### ISSUE THREAD

**Issue by yschimke** [jreleaser/jreleaser#626] opened 2021-12-26 21:08 UTC
### Task List

- [ ] Steps to reproduce provided
- [ ] Stacktrace (if present) provided
- [ ] Example that reproduces the problem (link to git repository is ideal)
- [ ] Full description of the issue provided (see below)

### Steps to Reproduce

1. publish release in github CI
2. include homebrew publishing step

**I suspect that the CI build for yschimke/okurl can't write to yschimke/homebrew-tap.**

### Expected Behaviour

Running locally

```
[INFO]  Publishing distributions
[INFO]    - Publishing okurl distribution
[INFO]      [brew] publishing okurl distribution
[INFO]      [brew] setting up repository yschimke/homebrew-tap
[INFO]      [brew] pushing to yschimke/homebrew-tap
[INFO]  Announcing releaseING [15s]
[INFO]  Announcing is not enabled. Skipping
[INFO]  Writing output properties to build/jreleaser/output.properties
[INFO]  JReleaser succeeded after 14.035 s

BUILD SUCCESSFUL in 16s
```

### Actual Behaviour

https://github.com/yschimke/okurl/runs/4637742898?check_suite_focus=true

```
 [INFO]  Publishing distributions
[INFO]    - Publishing okurl distribution
[INFO]      [brew] publishing okurl distribution
[INFO]      [brew] setting up repository yschimke/homebrew-tap
[INFO]      [brew] pushing to yschimke/homebrew-tap
[INFO]  Writing output properties to build/jreleaser/output.properties

[ERROR] JReleaser failed after 7.599 s
FAILURE: Build failed with an exception.


> Task :jreleaserFullRelease FAILED
* What went wrong:
Execution failed for task ':jreleaserFullRelease'.
> Unexpected error
```

### Environment Information

- **Operating System**: osx-latest in github
- **JReleaser Version:** 0.9.1
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.

**Comment by aalmiray** [comment] 2021-12-26 21:17
This behavior is explained here https://jreleaser.org/guide/latest/configuration/packagers/homebrew.html#_tokens

You need a Personal Access Token to push commits and tags to repositories other than the repository currently executing a workflow.

Closing as it's not a bug and the behavior is documented.

**Closed by aalmiray** 2021-12-26 21:17 UTC
Labels: invalid

**Comment by yschimke** [comment] 2021-12-26 21:24
Understood, I had assumed that as I mentioned in the bug report.  I was reporting this as it seems like there is some issue with the error reporting in this case. It doesn't give any error, just `FAILURE: Build failed with an exception.`

I'll change my job to print out the `./build/jreleaser/trace.log` manually which should have the error.
