### ISSUE TITLE
Fix "No JVMCI compiler found" with GraalVM CE 22.3.1 for Cross Platform JLINK projects

### ISSUE THREAD

**Issue by loiclefevre** [jreleaser/jreleaser#1275] opened 2023-03-15 14:45 UTC
### Steps to Reproduce

1. Use GraalVM CE 22.3.1 JVM for Cross Platform project using JLink
2. Extract generated zip file for non Windows OS
3. run the program, it should fail with the message: `Cannot use JVMCI compiler: No JVMCI compiler found`

### Expected Behaviour

It should work :)

### Actual Behaviour

Error message: `Cannot use JVMCI compiler: No JVMCI compiler found`

### Environment Information

- **Operating System**: Windows 10
- **JReleaser Version:** 1.5.1
- **JDK Version:** GraalVM CE 22.3.1 (OpenJDK 17.0.6)

[trace.log](https://github.com/jreleaser/jreleaser/files/10981150/trace.log)

**Comment by loiclefevre** [comment] 2023-03-15 14:48
After some investigations, it appears for all non Windows generated zip archive, the Windows related `bin/jvmcicompiler.dll` is present which is wrong.

For example, for MAC OS ARM, there should be the `libjvmcicompiler.dylib` file inside the `lib` folder as for other OS and architectures.

**Comment by aalmiray** [comment] 2023-03-15 17:07
Reproducer project can be found at https://github.com/aalmiray/helloworld-graalvm-jlink.

This appears to be a GraalVM + jlink issue as the following combinations were tested:

- running the build with regular JDK, targeting regular JDKs: no JVMCI. ✅ 
- running the build with regular JDK, targeting Graal JDKS: platform specific JVMCI shared across all assemblies. 🔴 
- running the build with Graal JDK, targeting Graal JDKS: platform specific JVMCI shared across all assemblies. 🔴

**Comment by aalmiray** [comment] 2023-03-15 17:17
Building the application on OSX yields the following:

```
$ ./out/jreleaser/assemble/helloworld/jlink/work-osx-x86_64/helloworld-1.0.0-SNAPSHOT-osx-x86_64/bin/helloworld
Hello world

$ ./out/jreleaser/assemble/helloworld/jlink/work-osx-x86_64/helloworld-1.0.0-SNAPSHOT-osx-x86_64/bin/java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 19.0.2+7-jvmci-22.3-b12)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 19.0.2+7-jvmci-22.3-b12, mixed mode)
```

The 3 Java runtimes look like this

**osx**
```
$ tree out/jreleaser/assemble/helloworld/jlink/work-osx-x86_64/helloworld-1.0.0-SNAPSHOT-osx-x86_64/
out/jreleaser/assemble/helloworld/jlink/work-osx-x86_64/helloworld-1.0.0-SNAPSHOT-osx-x86_64/
├── LICENSE
├── bin
│   ├── helloworld
│   ├── helloworld.bat
│   ├── java
│   └── keytool
├── conf
│   ├── net.properties
│   └── security
│       ├── java.policy
│       ├── java.security
│       └── policy
│           ├── README.txt
│           ├── limited
│           │   ├── default_US_export.policy
│           │   ├── default_local.policy
│           │   └── exempt_local.policy
│           └── unlimited
│               ├── default_US_export.policy
│               └── default_local.policy
├── jars
│   └── helloworld-1.0.0-SNAPSHOT.jar
├── legal
│   ├── java.base
│   │   ├── ADDITIONAL_LICENSE_INFO
│   │   ├── ASSEMBLY_EXCEPTION
│   │   ├── LICENSE
│   │   ├── aes.md
│   │   ├── asm.md
│   │   ├── c-libutl.md
│   │   ├── cldr.md
│   │   ├── icu.md
│   │   ├── public_suffix.md
│   │   └── unicode.md
│   └── jdk.internal.vm.ci
│       ├── ADDITIONAL_LICENSE_INFO -> ../java.base/ADDITIONAL_LICENSE_INFO
│       ├── ASSEMBLY_EXCEPTION -> ../java.base/ASSEMBLY_EXCEPTION
│       └── LICENSE -> ../java.base/LICENSE
├── lib
│   ├── classlist
│   ├── jrt-fs.jar
│   ├── jspawnhelper
│   ├── jvm.cfg
│   ├── libjava.dylib
│   ├── libjimage.dylib
│   ├── libjli.dylib
│   ├── libjsig.dylib
│   ├── libjvmcicompiler.dylib
│   ├── libnet.dylib
│   ├── libnio.dylib
│   ├── libosxsecurity.dylib
│   ├── libsyslookup.dylib
│   ├── libverify.dylib
│   ├── libzip.dylib
│   ├── modules
│   ├── security
│   │   ├── blocked.certs
│   │   ├── cacerts
│   │   ├── default.policy
│   │   └── public_suffix_list.dat
│   ├── server
│   │   ├── libjsig.dylib
│   │   └── libjvm.dylib
│   └── tzdb.dat
└── release
```

**linux**
```
$ tree out/jreleaser/assemble/helloworld/jlink/work-linux-x86_64/helloworld-1.0.0-SNAPSHOT-linux-x86_64/
out/jreleaser/assemble/helloworld/jlink/work-linux-x86_64/helloworld-1.0.0-SNAPSHOT-linux-x86_64/
├── LICENSE
├── bin
│   ├── helloworld
│   ├── helloworld.bat
│   ├── java
│   └── keytool
├── conf
│   ├── net.properties
│   ├── sdp
│   │   └── sdp.conf.template
│   └── security
│       ├── java.policy
│       ├── java.security
│       └── policy
│           ├── README.txt
│           ├── limited
│           │   ├── default_US_export.policy
│           │   ├── default_local.policy
│           │   └── exempt_local.policy
│           └── unlimited
│               ├── default_US_export.policy
│               └── default_local.policy
├── jars
│   └── helloworld-1.0.0-SNAPSHOT.jar
├── legal
│   ├── java.base
│   │   ├── ADDITIONAL_LICENSE_INFO
│   │   ├── ASSEMBLY_EXCEPTION
│   │   ├── LICENSE
│   │   ├── aes.md
│   │   ├── asm.md
│   │   ├── c-libutl.md
│   │   ├── cldr.md
│   │   ├── icu.md
│   │   ├── public_suffix.md
│   │   └── unicode.md
│   └── jdk.internal.vm.ci
│       ├── ADDITIONAL_LICENSE_INFO -> ../java.base/ADDITIONAL_LICENSE_INFO
│       ├── ASSEMBLY_EXCEPTION -> ../java.base/ASSEMBLY_EXCEPTION
│       └── LICENSE -> ../java.base/LICENSE
├── lib
│   ├── classlist
│   ├── jexec
│   ├── jrt-fs.jar
│   ├── jspawnhelper
│   ├── jvm.cfg
│   ├── libjava.so
│   ├── libjimage.so
│   ├── libjli.so
│   ├── libjsig.so
│   ├── libjvmcicompiler.dylib
│   ├── libnet.so
│   ├── libnio.so
│   ├── libsyslookup.so
│   ├── libverify.so
│   ├── libzip.so
│   ├── modules
│   ├── security
│   │   ├── blocked.certs
│   │   ├── cacerts
│   │   ├── default.policy
│   │   └── public_suffix_list.dat
│   ├── server
│   │   ├── libjsig.so
│   │   └── libjvm.so
│   └── tzdb.dat
└── release
```

**windows**
```
$ tree out/jreleaser/assemble/helloworld/jlink/work-windows-x86_64/helloworld-1.0.0-SNAPSHOT-windows-x86_64/
out/jreleaser/assemble/helloworld/jlink/work-windows-x86_64/helloworld-1.0.0-SNAPSHOT-windows-x86_64/
├── LICENSE
├── bin
│   ├── api-ms-win-core-console-l1-1-0.dll
│   ├── api-ms-win-core-console-l1-2-0.dll
│   ├── api-ms-win-core-datetime-l1-1-0.dll
│   ├── api-ms-win-core-debug-l1-1-0.dll
│   ├── api-ms-win-core-errorhandling-l1-1-0.dll
│   ├── api-ms-win-core-file-l1-1-0.dll
│   ├── api-ms-win-core-file-l1-2-0.dll
│   ├── api-ms-win-core-file-l2-1-0.dll
│   ├── api-ms-win-core-handle-l1-1-0.dll
│   ├── api-ms-win-core-heap-l1-1-0.dll
│   ├── api-ms-win-core-interlocked-l1-1-0.dll
│   ├── api-ms-win-core-libraryloader-l1-1-0.dll
│   ├── api-ms-win-core-localization-l1-2-0.dll
│   ├── api-ms-win-core-memory-l1-1-0.dll
│   ├── api-ms-win-core-namedpipe-l1-1-0.dll
│   ├── api-ms-win-core-processenvironment-l1-1-0.dll
│   ├── api-ms-win-core-processthreads-l1-1-0.dll
│   ├── api-ms-win-core-processthreads-l1-1-1.dll
│   ├── api-ms-win-core-profile-l1-1-0.dll
│   ├── api-ms-win-core-rtlsupport-l1-1-0.dll
│   ├── api-ms-win-core-string-l1-1-0.dll
│   ├── api-ms-win-core-synch-l1-1-0.dll
│   ├── api-ms-win-core-synch-l1-2-0.dll
│   ├── api-ms-win-core-sysinfo-l1-1-0.dll
│   ├── api-ms-win-core-timezone-l1-1-0.dll
│   ├── api-ms-win-core-util-l1-1-0.dll
│   ├── api-ms-win-crt-conio-l1-1-0.dll
│   ├── api-ms-win-crt-convert-l1-1-0.dll
│   ├── api-ms-win-crt-environment-l1-1-0.dll
│   ├── api-ms-win-crt-filesystem-l1-1-0.dll
│   ├── api-ms-win-crt-heap-l1-1-0.dll
│   ├── api-ms-win-crt-locale-l1-1-0.dll
│   ├── api-ms-win-crt-math-l1-1-0.dll
│   ├── api-ms-win-crt-multibyte-l1-1-0.dll
│   ├── api-ms-win-crt-private-l1-1-0.dll
│   ├── api-ms-win-crt-process-l1-1-0.dll
│   ├── api-ms-win-crt-runtime-l1-1-0.dll
│   ├── api-ms-win-crt-stdio-l1-1-0.dll
│   ├── api-ms-win-crt-string-l1-1-0.dll
│   ├── api-ms-win-crt-time-l1-1-0.dll
│   ├── api-ms-win-crt-utility-l1-1-0.dll
│   ├── helloworld
│   ├── helloworld.bat
│   ├── java.dll
│   ├── java.exe
│   ├── javaw.exe
│   ├── jimage.dll
│   ├── jli.dll
│   ├── keytool.exe
│   ├── msvcp140.dll
│   ├── net.dll
│   ├── nio.dll
│   ├── server
│   │   └── jvm.dll
│   ├── syslookup.dll
│   ├── ucrtbase.dll
│   ├── vcruntime140.dll
│   ├── vcruntime140_1.dll
│   ├── verify.dll
│   └── zip.dll
├── conf
│   ├── net.properties
│   └── security
│       ├── java.policy
│       ├── java.security
│       └── policy
│           ├── README.txt
│           ├── limited
│           │   ├── default_US_export.policy
│           │   ├── default_local.policy
│           │   └── exempt_local.policy
│           └── unlimited
│               ├── default_US_export.policy
│               └── default_local.policy
├── jars
│   └── helloworld-1.0.0-SNAPSHOT.jar
├── legal
│   ├── java.base
│   │   ├── ADDITIONAL_LICENSE_INFO
│   │   ├── ASSEMBLY_EXCEPTION
│   │   ├── LICENSE
│   │   ├── aes.md
│   │   ├── asm.md
│   │   ├── c-libutl.md
│   │   ├── cldr.md
│   │   ├── icu.md
│   │   ├── public_suffix.md
│   │   ├── unicode.md
│   │   ├── wepoll.md
│   │   └── zlib.md
│   └── jdk.internal.vm.ci
│       ├── ADDITIONAL_LICENSE_INFO
│       ├── ASSEMBLY_EXCEPTION
│       └── LICENSE
├── lib
│   ├── classlist
│   ├── jrt-fs.jar
│   ├── jvm.cfg
│   ├── jvm.lib
│   ├── libjvmcicompiler.dylib
│   ├── modules
│   ├── security
│   │   ├── blocked.certs
│   │   ├── cacerts
│   │   ├── default.policy
│   │   └── public_suffix_list.dat
│   ├── tzdb.dat
│   └── tzmappings
└── release
```


Notice all of them have `libjvmcicompiler.dylib` which is wrong for Linux and Windows. Building these JRs using a non Graal JDK does not copy said binary into the target JRs.

**Comment by aalmiray** [comment] 2023-03-15 17:18
One more thing, running the linux executable on Docker appears to work fine

```
$ docker run -it --rm -v /tmp/hw/out/jreleaser/assemble/helloworld/jlink/work-linux-x86_64/helloworld-1.0.0-SNAPSHOT-linux-x86_64:/work --entrypoint /bin/sh ubuntu:latest		
# ls /work
LICENSE  bin  conf  jars  legal  lib  release
# /work/bin/helloworld
Hello world
```

**Comment by aalmiray** [comment] 2023-03-15 17:36
It's worth noting that JReleaser invokes `jlink` under the hood as an external program, like so

```
/private/tmp/hw/target/jdks/graalvm22OsxIntel/graalvm-ce-java19-22.3.1/Contents/Home/bin/jlink --no-header-files --no-man-pages --compress=2 --strip-debug --module-path /private/tmp/hw/target/jdks/graalvm22LinuxIntel/graalvm-ce-java19-22.3.1/jmods:/private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/inputs/jars/universal --add-modules java.base --output /private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/work-linux-x86_64/helloworld-1.0.0-SNAPSHOT-linux-x86_64
```

```
/private/tmp/hw/target/jdks/graalvm22OsxIntel/graalvm-ce-java19-22.3.1/Contents/Home/bin/jlink --no-header-files --no-man-pages --compress=2 --strip-debug --module-path /private/tmp/hw/target/jdks/graalvm22OsxIntel/graalvm-ce-java19-22.3.1/Contents/Home/jmods:/private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/inputs/jars/universal --add-modules java.base --output /private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/work-osx-x86_64/helloworld-1.0.0-SNAPSHOT-osx-x86_64
```

```
/private/tmp/hw/target/jdks/graalvm22OsxIntel/graalvm-ce-java19-22.3.1/Contents/Home/bin/jlink --no-header-files --no-man-pages --compress=2 --strip-debug --module-path /private/tmp/hw/target/jdks/graalvm22WindowsIntel/graalvm-ce-java19-22.3.1/jmods:/private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/inputs/jars/universal --add-modules java.base --output /private/tmp/hw/out/jreleaser/assemble/helloworld/jlink/work-windows-x86_64/helloworld-1.0.0-SNAPSHOT-windows-x86_64
```

**Comment by gilles-duboscq** [comment] 2023-03-16 09:55
From the command lines above i see that a "cross platform jlink" is actually achieved by by pointing jlink to jmods from another platform with --module-path. Since the jvmcicompiler is not part of any jmod but just copied from the current JDK to the output by a jlink plugin, this means it always uses the library from the platform used to run jlink

This should be fixed in the next GraalVM release thanks to https://github.com/oracle/graal/pull/5264.

**Comment by aalmiray** [comment] 2023-03-19 18:00
Closing as it's not a JReleaser issue.

**Closed by aalmiray** 2023-03-19 18:00 UTC
Labels: invalid
