### ISSUE TITLE
[deploy] NPE trying to deploy to nexus/central

### ISSUE THREAD

**Issue by evanchooly** [jreleaser/jreleaser#1460] opened 2023-08-04 04:55 UTC
### Task List
- the pom used can be found [here](https://github.com/evanchooly/obsoleter/blob/931c59b5d75218079db3525bcf95a7a84d58276d/pom.xml#L125)
- the stacktrace can be found [https://github.com/evanchooly/obsoleter/actions/runs/5758444813/job/15611000788](here)  (But i'll include it at the bottom, too.)

### Steps to Reproduce

1. i run the deploy via GH actions with the mvn command:  `mvn -e -Plocal-deploy -Drelease deploy jreleaser:full-release`.
2. the workflow file can be found [here](https://github.com/evanchooly/obsoleter/blob/e5cf462fa0e70a182a726f52ac644fc3a1bfe19f/.github/workflows/release.yml#L40)
3. the trace.log shows a 403 on my setup (I'll plonk away on that) but the only indication to the user is an unhelpful [NPE.](url)

### Expected Behaviour

Smiles and sunshine.

### Actual Behaviour

Frowny faces and sad thoughts.

### Environment Information

- **JReleaser Version:** 1.7.0
- **JDK Version:** 17

Please paste stacktraces from `[out|build|target]/jreleaser/trace.log`.
[trace.log](https://github.com/jreleaser/jreleaser/files/12257183/trace.log)

**Comment by aalmiray** [comment] 2023-08-04 05:44
Might be a duplicate of #1445 based on the URL seen at the log `https://s01.oss.sonatype.org/content/repositories/snapshots//com/antwerkz/maven/maven-metadata.xml`

**Comment by evanchooly** [comment] 2023-08-05 02:34
the url was definitely the problem but in a different way.  I needed to change my repo urls because my sonatype account uses the old url.  Once I did that, no more 403.

**Comment by aalmiray** [comment] 2023-08-05 04:00
Gotcha

**Closed** 2023-08-06 15:01 UTC
