### ISSUE TITLE
[release] 1.6.0 failing to publish to a branch

### ISSUE THREAD

**Issue by michael-simons** [jreleaser/jreleaser#1388] opened 2023-05-16 08:42 UTC
I upgraded from 1.5.1 to 1.6.0 and it fails me when doing the release:

https://github.com/michael-simons/neo4j-migrations/actions/runs/4989422956/jobs/8933639233#step:6:95

```
[INFO] Releasing to https://github.com/michael-simons/neo4j-migrations@main
[INFO] Writing output properties to target/jreleaser/output.properties
Error:  JReleaser failed after 1.782 s
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  11.870 s
[INFO] Finished at: 2023-05-16T08:22:14Z
[INFO] ------------------------------------------------------------------------
Error:  Failed to execute goal org.jreleaser:jreleaser-maven-plugin:1.6.0:full-release (default-cli) on project neo4j-migrations-parent: Execution default-cli of goal org.jreleaser:jreleaser-maven-plugin:1.6.0:full-release failed: Unexpected error when creating release: java.io.IOException: Could not checkout branch main: Ref main cannot be resolved -> [Help 1]
```

Reverting back to 1.5.1 resolved this for me.

This is the failing workflow: https://github.com/michael-simons/neo4j-migrations/blob/main/.github/workflows/release.yml#L147

**Comment by aalmiray** [comment] 2023-05-16 08:49
Might be a duplicate of https://github.com/jreleaser/jreleaser/issues/1377

**Closed** 2023-05-16 13:40 UTC
Labels: bug, duplicate
